### ISSUE TITLE
create new release for NPM

### ISSUE THREAD

**Issue by tylev** [joule-labs/react-webln-fallback#17]
Hey @wbobeirne, noticed the versions 0.1.14 on NPM aren't updated with the `MakeInvoice` payment request bugfix you added in [fdcd40](https://github.com/joule-labs/react-webln-fallback/commit/fdcd407b3e1514ca1a7d12e9f1ce3e7433935a40). Could you bump the versions and republish please? 🙏

**Comment by wbobeirne** [comment]
Hey @tylev, thanks for the reminder, can't believe I failed to do that. Currently trying to upgrade far too many out of date packages before putting out a new release as a few vulnerabilities and new versions of UI libraries have cropped up, and I want to make sure I'm putting out a package that works with the latest.

Was there a particular package you were using that I could prioritize?

**Comment by tylev** [comment]
appreciate it @wbobeirne, I'm using the `antd` flavor but I found a temp workaround for now, so no rush. I'm also planing on building a version that works with Chakra UI.

**Comment by wbobeirne** [comment]
Closed with `0.2.1` up. Can't apologize enough for totally dropping this, but this brings everything back up to speed and will make subsequent releases way less of a headache.
