### ISSUE TITLE
MakeInvoice component doesn't return the payment request.

### ISSUE THREAD

**Issue by kwuenscher** [joule-labs/react-webln-fallback#2]
This 
```
private handleApprove = () => {
    this.props.onApprove({ paymentRequest: '' } as RequestInvoiceResponse);
  };
```
should be changed to something like this 
```
private handleApprove = () => {
    this.props.onApprove({ paymentRequest: this.state.paymentRequest } as RequestInvoiceResponse);
  };
```
otherwise the payment request is not returned.

**Comment by wbobeirne** [comment]
Wow, I have no idea where my head was at when I wrote that line, that's obviously what it should be. Thanks for the heads up, I'll try to get a new release out ASAP.

**Comment by wbobeirne** [comment]
This is finally up in the published releases.
